# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /data/data/com.termux/files/usr/bin/sh

# The CMake executable.
CMAKE_COMMAND = /data/data/com.termux/files/usr/bin/cmake

# The command to remove a file.
RM = /data/data/com.termux/files/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /data/data/com.termux/files/home/ncmdump

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /data/data/com.termux/files/home/ncmdump

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/data/data/com.termux/files/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/data/data/com.termux/files/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/data/data/com.termux/files/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/data/data/com.termux/files/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/data/data/com.termux/files/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/ncmdump/CMakeFiles /data/data/com.termux/files/home/ncmdump//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /data/data/com.termux/files/home/ncmdump/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ncmdump

# Build rule for target.
ncmdump: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ncmdump
.PHONY : ncmdump

# fast build rule for target.
ncmdump/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump.dir/build.make CMakeFiles/ncmdump.dir/build
.PHONY : ncmdump/fast

#=============================================================================
# Target rules for targets named ncmdump_exec

# Build rule for target.
ncmdump_exec: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ncmdump_exec
.PHONY : ncmdump_exec

# fast build rule for target.
ncmdump_exec/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/build
.PHONY : ncmdump_exec/fast

#=============================================================================
# Target rules for targets named docs

# Build rule for target.
docs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 docs
.PHONY : docs

# fast build rule for target.
docs/fast:
	$(MAKE) $(MAKESILENT) -f taglib/CMakeFiles/docs.dir/build.make taglib/CMakeFiles/docs.dir/build
.PHONY : docs/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f taglib/CMakeFiles/uninstall.dir/build.make taglib/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named tag

# Build rule for target.
tag: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tag
.PHONY : tag

# fast build rule for target.
tag/fast:
	$(MAKE) $(MAKESILENT) -f taglib/taglib/CMakeFiles/tag.dir/build.make taglib/taglib/CMakeFiles/tag.dir/build
.PHONY : tag/fast

#=============================================================================
# Target rules for targets named tag_c

# Build rule for target.
tag_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tag_c
.PHONY : tag_c

# fast build rule for target.
tag_c/fast:
	$(MAKE) $(MAKESILENT) -f taglib/bindings/c/CMakeFiles/tag_c.dir/build.make taglib/bindings/c/CMakeFiles/tag_c.dir/build
.PHONY : tag_c/fast

src/lib/libncmdump.o: src/lib/libncmdump.cpp.o
.PHONY : src/lib/libncmdump.o

# target to build an object file
src/lib/libncmdump.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump.dir/build.make CMakeFiles/ncmdump.dir/src/lib/libncmdump.cpp.o
.PHONY : src/lib/libncmdump.cpp.o

src/lib/libncmdump.i: src/lib/libncmdump.cpp.i
.PHONY : src/lib/libncmdump.i

# target to preprocess a source file
src/lib/libncmdump.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump.dir/build.make CMakeFiles/ncmdump.dir/src/lib/libncmdump.cpp.i
.PHONY : src/lib/libncmdump.cpp.i

src/lib/libncmdump.s: src/lib/libncmdump.cpp.s
.PHONY : src/lib/libncmdump.s

# target to generate assembly for a file
src/lib/libncmdump.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump.dir/build.make CMakeFiles/ncmdump.dir/src/lib/libncmdump.cpp.s
.PHONY : src/lib/libncmdump.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/ncmcrypt.o: src/ncmcrypt.cpp.o
.PHONY : src/ncmcrypt.o

# target to build an object file
src/ncmcrypt.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/ncmcrypt.cpp.o
.PHONY : src/ncmcrypt.cpp.o

src/ncmcrypt.i: src/ncmcrypt.cpp.i
.PHONY : src/ncmcrypt.i

# target to preprocess a source file
src/ncmcrypt.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/ncmcrypt.cpp.i
.PHONY : src/ncmcrypt.cpp.i

src/ncmcrypt.s: src/ncmcrypt.cpp.s
.PHONY : src/ncmcrypt.s

# target to generate assembly for a file
src/ncmcrypt.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/ncmcrypt.cpp.s
.PHONY : src/ncmcrypt.cpp.s

src/utils/aes.o: src/utils/aes.cpp.o
.PHONY : src/utils/aes.o

# target to build an object file
src/utils/aes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/utils/aes.cpp.o
.PHONY : src/utils/aes.cpp.o

src/utils/aes.i: src/utils/aes.cpp.i
.PHONY : src/utils/aes.i

# target to preprocess a source file
src/utils/aes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/utils/aes.cpp.i
.PHONY : src/utils/aes.cpp.i

src/utils/aes.s: src/utils/aes.cpp.s
.PHONY : src/utils/aes.s

# target to generate assembly for a file
src/utils/aes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/utils/aes.cpp.s
.PHONY : src/utils/aes.cpp.s

src/utils/cJSON.o: src/utils/cJSON.cpp.o
.PHONY : src/utils/cJSON.o

# target to build an object file
src/utils/cJSON.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/utils/cJSON.cpp.o
.PHONY : src/utils/cJSON.cpp.o

src/utils/cJSON.i: src/utils/cJSON.cpp.i
.PHONY : src/utils/cJSON.i

# target to preprocess a source file
src/utils/cJSON.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/utils/cJSON.cpp.i
.PHONY : src/utils/cJSON.cpp.i

src/utils/cJSON.s: src/utils/cJSON.cpp.s
.PHONY : src/utils/cJSON.s

# target to generate assembly for a file
src/utils/cJSON.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ncmdump_exec.dir/build.make CMakeFiles/ncmdump_exec.dir/src/utils/cJSON.cpp.s
.PHONY : src/utils/cJSON.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... docs"
	@echo "... uninstall"
	@echo "... ncmdump"
	@echo "... ncmdump_exec"
	@echo "... tag"
	@echo "... tag_c"
	@echo "... src/lib/libncmdump.o"
	@echo "... src/lib/libncmdump.i"
	@echo "... src/lib/libncmdump.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/ncmcrypt.o"
	@echo "... src/ncmcrypt.i"
	@echo "... src/ncmcrypt.s"
	@echo "... src/utils/aes.o"
	@echo "... src/utils/aes.i"
	@echo "... src/utils/aes.s"
	@echo "... src/utils/cJSON.o"
	@echo "... src/utils/cJSON.i"
	@echo "... src/utils/cJSON.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

